"""
ChromaDB-backed vector store for RAG retrieval.

Embeddings are generated by Jina AI (src/embeddings.py) and stored in
ChromaDB for persistent, queryable storage.  Each paper gets its own
ChromaDB collection (keyed by sanitised arXiv ID), so:
  - Multiple papers can coexist without interference
  - Sessions persist across CLI invocations
  - Embeddings are never recomputed for already-indexed papers
"""
from __future__ import annotations

import re
from typing import List, Tuple

import chromadb
import numpy as np

from .config import CHROMA_PERSIST_DIR
from .embeddings import embed_texts, embed_query
from .models import Chunk


def _sanitize_collection_name(arxiv_id: str) -> str:
    """
    ChromaDB collection names must be 3-63 chars, start/end with alnum,
    and contain only alnum, underscores, hyphens.
    """
    name = f"paper_{re.sub(r'[^a-zA-Z0-9_-]', '_', arxiv_id)}"
    # Ensure length constraints
    if len(name) < 3:
        name = name + "_col"
    return name[:63]


def _get_client() -> chromadb.PersistentClient:
    """Get or create a persistent ChromaDB client."""
    CHROMA_PERSIST_DIR.mkdir(parents=True, exist_ok=True)
    return chromadb.PersistentClient(path=str(CHROMA_PERSIST_DIR))


def index_chunks(chunks: List[Chunk], arxiv_id: str) -> str:
    """
    Embed chunks via Jina AI and store them in ChromaDB.

    Returns the collection name (used later for querying).
    If the collection already exists with the same number of documents,
    skip re-indexing (embeddings are already stored).
    """
    collection_name = _sanitize_collection_name(arxiv_id)
    client = _get_client()

    # Get or create the collection
    collection = client.get_or_create_collection(
        name=collection_name,
        metadata={"hnsw:space": "cosine"},
    )

    # Skip re-indexing if already populated
    if collection.count() >= len(chunks):
        return collection_name

    # Generate embeddings via Jina AI
    texts = [c.text for c in chunks]
    vectors = embed_texts(texts)

    # Add to ChromaDB
    collection.add(
        ids=[f"chunk_{c.id}" for c in chunks],
        embeddings=vectors.tolist(),
        documents=texts,
        metadatas=[{"chunk_id": c.id, "section_hint": c.section_hint or ""} for c in chunks],
    )

    return collection_name


def search(collection_name: str, query: str, top_k: int = 4) -> List[Tuple[str, float]]:
    """
    Search the vector store for chunks relevant to a query.

    Returns a list of (chunk_text, similarity_score) tuples,
    sorted by relevance (highest first).
    """
    client = _get_client()

    try:
        collection = client.get_collection(name=collection_name)
    except Exception:
        return []

    if collection.count() == 0:
        return []

    # Embed the query via Jina AI
    query_vector = embed_query(query)

    results = collection.query(
        query_embeddings=query_vector.tolist(),
        n_results=min(top_k, collection.count()),
        include=["documents", "distances"],
    )

    # ChromaDB returns distances (lower = more similar for cosine).
    # Convert to similarity scores: similarity = 1 - distance
    pairs = []
    if results["documents"] and results["distances"]:
        for doc, dist in zip(results["documents"][0], results["distances"][0]):
            similarity = 1.0 - dist
            pairs.append((doc, similarity))

    return pairs


def collection_exists(arxiv_id: str) -> bool:
    """Check if a paper has already been indexed."""
    collection_name = _sanitize_collection_name(arxiv_id)
    client = _get_client()
    try:
        col = client.get_collection(name=collection_name)
        return col.count() > 0
    except Exception:
        return False
